// Runs Grounded UI contracts against an outside implementation's published examples and writes a report.
// Usage: node reports/run.mjs <implementation-folder>   e.g. node reports/run.mjs govuk-frontend
// Reads reports/<impl>/report.yaml; writes reports/<impl>/<component>.json and .md.
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { join } from 'node:path';
import { parse } from 'yaml';
import { chromium } from '@playwright/test';
import { checkPage, loadBinding, loadContracts } from '../conformance/src/index.mjs';

const require = createRequire(import.meta.url);
const impl = process.argv[2];
if (!impl) throw new Error('usage: node reports/run.mjs <implementation-folder>');
const dir = new URL(impl + '/', import.meta.url).pathname;
const config = parse(readFileSync(join(dir, 'report.yaml'), 'utf8'));
const version = JSON.parse(readFileSync(require.resolve(`${config.package}/package.json`), 'utf8')).version;
const contracts = loadContracts();

const browser = await chromium.launch();
const page = await (await browser.newContext()).newPage();

for (const [slug, spec] of Object.entries(config.components)) {
  const contract = contracts[slug];
  const binding = loadBinding(join(dir, spec.binding));
  const examples = spec.fixtures.flatMap((file) =>
    JSON.parse(readFileSync(require.resolve(file), 'utf8')).fixtures
      .filter((f) => !f.hidden)
      .map((f) => ({ source: file.split('/').at(-2), name: f.name, html: f.html })),
  );

  const rows = [];
  for (const example of examples) {
    await page.setContent(`<!doctype html><html lang="en"><body>${example.html}</body></html>`);
    const report = await checkPage(page, { contracts: { [slug]: contract }, bindings: { [slug]: binding } });
    rows.push({ ...example, report });
  }

  // Per rule: in how many examples it failed, and in how many of those axe reported nothing at all.
  const byRule = contract.rules.map((rule) => {
    const failing = rows.filter((row) => row.report.some((root) => root.results.some((r) => r.id === rule.id && !r.pass)));
    const axeSilent = failing.filter((row) => row.report.every((root) => root.axeViolations.length === 0));
    const detail = failing[0]?.report.flatMap((root) => root.results).find((r) => r.id === rule.id && !r.pass)?.detail;
    return { id: rule.id, level: rule.level, description: rule.description, failing: failing.map((r) => `${r.source}: ${r.name}`), axeSilent: axeSilent.length, detail };
  });
  const tested = rows.filter((row) => row.report.length).length;
  const axeTotal = rows.reduce((n, row) => n + row.report.reduce((m, root) => m + root.axeViolations.length, 0), 0);

  writeFileSync(join(dir, `${slug}.json`), JSON.stringify({ implementation: config.implementation, version, contract: contract.contractVersion, examples: rows }, null, 2) + '\n');

  const md = [
    `# ${config.implementation} ${version} × Grounded UI ${slug} contract ${contract.contractVersion}`,
    '',
    `Generated by \`node reports/run.mjs ${impl}\`. ${tested} of ${examples.length} published examples contained a ${slug}; axe reported ${axeTotal} violation(s) across them.`,
    '',
    '| Rule | Level | Failing examples | Of those, axe silent | Example detail |',
    '| --- | --- | ---: | ---: | --- |',
    ...byRule.map((r) => `| ${r.id} ${r.description} | ${r.level} | ${r.failing.length} | ${r.failing.length ? r.axeSilent : '—'} | ${r.detail ? r.detail.replace(/\|/g, '\\|') : ''} |`),
    '',
    ...byRule.filter((r) => r.failing.length).flatMap((r) => [`## ${r.id}`, '', ...r.failing.map((f) => `- ${f}`), '']),
  ].join('\n');
  writeFileSync(join(dir, `${slug}.md`), md);
  console.log(md);
}
await browser.close();
